version: '3.8'

services:
  telegram-bot:
    build: .

    volumes:
      - .:/app
      
    environment:
      - TOKEN=${TOKEN}

    healthcheck:
      test: ["CMD-SHELL", "pgrep -f python || exit 1"]

    restart: unless-stopped